# Builds, tests and publishes to maven when a release is published
name: Release Tests

on:
  release:
    types: [ published ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build test
      - name: Upload GitHub Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Plugin Jar
          path: target/PAPIProxyBridge-Plugin-*.jar